### ISSUE TITLE
lii2123 

### ISSUE THREAD

**Issue by lii2123** [bcb420-2024/Student-wiki#1]

**Comment by risserlin** [comment]
Student name: ????
GitHub username: lii2123

Please add your student name

**Comment by lii2123** [comment]
Student name: Isabel Li

**Comment by risserlin** [comment]
created repo - [Isabel Li](https://github.com/bcb420-2024/Isabel_Li) in the [bcb420-2024](https://github.com/bcb420-2024) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
