### ISSUE TITLE
A-mos1

### ISSUE THREAD

**Issue by A-mos1** [bcb420-2024/Student-wiki#11]
Student name: Ahmed Moselhi
Github username: A-mos1

**Comment by risserlin** [comment]
created repo - [Ahmed Moselhi](https://github.com/bcb420-2024/Ahmed_Moselhi) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
