### ISSUE TITLE
michellemlin

### ISSUE THREAD

**Issue by michellemlin** [bcb420-2024/Student-wiki#14]
Student Name: Michelle Lin
Github Username: michellemlin

**Comment by michellemlin** [comment]
Student Name: Michelle Lin
Github Username: michellemlin

**Comment by risserlin** [comment]
created repo - [Michelle Lin](https://github.com/bcb420-2024/Michelle_Lin) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
