### ISSUE TITLE
ElKju

### ISSUE THREAD

**Issue by ElKju** [bcb420-2024/Student-wiki#15]
Student Name: Li Quan Soh
Github Username: ElKju

**Comment by risserlin** [comment]
created repo - [Li Soh](https://github.com/bcb420-2024/Li_Soh) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
