### ISSUE TITLE
bdls-jamal

### ISSUE THREAD

**Issue by bdls-jamal** [bcb420-2024/Student-wiki#18]

**Comment by risserlin** [comment]
Student name: ????
GitHub username: bdls-jamal

Please add your student name

**Comment by bdls-jamal** [comment]
Student name: Kobi Schmalenberg
GitHub username: bdls-jamal

Sorry, my mistake

**Comment by risserlin** [comment]
created repo - [Kobi Schmalenberg](https://github.com/bcb420-2024/Kobi_Schmalenberg) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
