### ISSUE TITLE
MikaelLeonard

### ISSUE THREAD

**Issue by MikaelLeonard** [bcb420-2024/Student-wiki#19]
student name: Mikael Gouwtama
github username: MikaelLeonard

**Comment by risserlin** [comment]
created repo - [Mikael Gouwtama](https://github.com/bcb420-2024/Mikael_Gouwtama) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
