### ISSUE TITLE
leeti2

### ISSUE THREAD

**Issue by leeti2** [bcb420-2024/Student-wiki#2]

**Comment by risserlin** [comment]
Student name: ????
GitHub username: leeti2

Please add your student name

**Comment by leeti2** [comment]
Student Name: Tiana Lee 
GitHub username: leeti2

**Comment by risserlin** [comment]
created repo - [Tiana Lee](https://github.com/bcb420-2024/Tiana_Lee) in the [bcb420-2024](https://github.com/bcb420-2024) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
