### ISSUE TITLE
Mogtaba-Alim

### ISSUE THREAD

**Issue by Mogtaba-Alim** [bcb420-2024/Student-wiki#23]
Student Name: Mogtaba Alim
Github: Mogtaba-Alim

**Comment by risserlin** [comment]
created repo - [Mogtaba Alim](https://github.com/bcb420-2024/Mogtaba_Alim) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know
