### ISSUE TITLE
Harrison Deng

### ISSUE THREAD

**Issue by RealYHD** [bcb420-2024/Student-wiki#25]
Student Name: Harrison Deng
GitHub Username: RealYHD

**Comment by risserlin** [comment]
created repo - [Harrison Deng](https://github.com/bcb420-2024/Harrison_Deng) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know
