### ISSUE TITLE
Dien Nguyen

### ISSUE THREAD

**Issue by dien-n-nguyen** [bcb420-2024/Student-wiki#26]
Student name: Dien Nguyen
GitHub name: dien-n-nguyen

**Comment by risserlin** [comment]
created repo - [Dien Nguyen](https://github.com/bcb420-2024/Dien_Nguyen) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know
