### ISSUE TITLE
vishali-u

### ISSUE THREAD

**Issue by vishali-u** [bcb420-2024/Student-wiki#29]
Student name: Vishali Umaiyalan
Github username: vishali-u

**Comment by risserlin** [comment]
created repo - [Vishali Umaiyalan](https://github.com/bcb420-2024/Vishali_Umaiyalan) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know
