### ISSUE TITLE
kevqyzhu

### ISSUE THREAD

**Issue by kevqyzhu** [bcb420-2024/Student-wiki#3]

**Comment by risserlin** [comment]
Student name: ????
GitHub username: kevqyzhu

Please add your student name

**Comment by kevqyzhu** [comment]
Student name: Kevin Zhu
GitHub username: kevqyzhu

**Comment by risserlin** [comment]
created repo - [Kevin zhu](https://github.com/bcb420-2024/Kevin_Zhu) in the [bcb420-2024](https://github.com/bcb420-2024) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
