### ISSUE TITLE
gerd-bizi

### ISSUE THREAD

**Issue by gerd-bizi** [bcb420-2024/Student-wiki#30]
Step 1 for Account Set Up
Name: Gerd Bizi
Github User: gerd-bizi

**Comment by risserlin** [comment]
created repo - [Gerd Bizi](https://github.com/bcb420-2024/Gerd_Bizi) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know
