### ISSUE TITLE
AnnaTLai

### ISSUE THREAD

**Issue by AnnaTLai** [bcb420-2024/Student-wiki#33]
Anna L. BCB420 github username: AnnaTLai

**Comment by risserlin** [comment]
created repo - [Anna Lai](https://github.com/bcb420-2024/Anna_Lai) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know
