### ISSUE TITLE
Maheen Riaz

### ISSUE THREAD

**Issue by maheen1riaz** [bcb420-2024/Student-wiki#34]
For BCB420 Repo

Student name: Maheen Riaz 
username: maheen1riaz

**Comment by maheen1riaz** [comment]
Link to my Wiki: https://github.com/bcb420-2024/Maheen_Riaz/wiki

I am unable to add it to the master list

**Comment by risserlin** [comment]
Sorry.  I forgot to add the new users name to the Student Wiki as well.  I have added it now.  I didn't deduct marks for not having the link to your wiki on the Student wiki but please add it when you get a chance.  
Thanks, 
Ruth

**Comment by maheen1riaz** [comment]
Just added it. Thank you, Professor!
