### ISSUE TITLE
Ishmal Amir

### ISSUE THREAD

**Issue by ishmala** [bcb420-2024/Student-wiki#36]
For BCB420 Repo

Student Name: Ishmal Amir
Username: ishmala

**Comment by risserlin** [comment]
created repo - [Ishmal Amir](https://github.com/bcb420-2024/Ishmal_Amir) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know
