### ISSUE TITLE
jamesshi567

### ISSUE THREAD

**Issue by jamesshi567** [bcb420-2024/Student-wiki#4]
Student name: James Shi
Github username: jamesshi567

**Comment by risserlin** [comment]
created repo - [James Shi](https://github.com/bcb420-2024/James_Shi) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
