### ISSUE TITLE
MAM122

### ISSUE THREAD

**Issue by MAM122** [bcb420-2024/Student-wiki#5]
Student Name: Matea Maurice
Github username: MAM122

**Comment by risserlin** [comment]
created repo - [Matea Maurice](https://github.com/bcb420-2024/Matea_Maurice) in the [bcb420-2024](https://github.com/bcb420-2024) organizations and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
