### ISSUE TITLE
wk1267

### ISSUE THREAD

**Issue by wk1267** [bcb420-2024/Student-wiki#6]
Student name: Koh Zhi Cong Windsor (or  Koh Windsor )
github: wk1267

**Comment by risserlin** [comment]
created repo - [Koh Windsor](https://github.com/bcb420-2024/Koh_Windsor) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
