### ISSUE TITLE
Student name: Yunyi Cheng GitHub username: yunyicheng

### ISSUE THREAD

**Issue by yunyicheng** [bcb420-2024/Student-wiki#8]

**Comment by risserlin** [comment]
created repo - [Yunyi Cheng](https://github.com/bcb420-2024/Yunyi_Cheng) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
