### ISSUE TITLE
ika-joshi

### ISSUE THREAD

**Issue by ika-joshi** [bcb420-2024/Student-wiki#9]
Student name: Krutika Joshi
GitHub name: ika-joshi

**Comment by risserlin** [comment]
created repo - [Krutika Joshi](https://github.com/bcb420-2024/Krutika_Joshi) in the [bcb420-2024](https://github.com/bcb420-2024) organization and added you to the [Students team](https://github.com/orgs/bcb420-2024/teams/students). You can now set up your wiki and add info to the student wiki. you should have received invitations to the repo and the team.
Looking forward to a productive semester. If you have any issues please let me know.
